[versions]
com-fasterxml-jackson = "2.20.1"
info-picocli = "4.7.7"
org-slf4j = "2.0.17"
junit-platform = "6.0.1" # Přidána verze pro junit-platform
org-junit-jupiter = "6.0.1"

[libraries]
com-fasterxml-jackson-core-jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "com-fasterxml-jackson" }
com-fasterxml-jackson-dataformat-jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "com-fasterxml-jackson" }
com-vdurmont-semver4j = "com.vdurmont:semver4j:3.1.0"
info-picocli = { module = "info.picocli:picocli", version.ref = "info-picocli" }
info-picocli-picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "info-picocli" }
org-apache-commons-commons-collections4 = "org.apache.commons:commons-collections4:4.5.0"
org-apache-commons-commons-io = "commons-io:commons-io:2.21.0"
org-apache-commons-commons-text = "org.apache.commons:commons-text:1.14.0"
org-junit-jupiter-junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "org-junit-jupiter" }
org-junit-jupiter-junit-jupiter = "org.junit.jupiter:junit-jupiter:6.0.1"
org-junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" } # Přidáno
org-junit-junit-bom = "org.junit:junit-bom:6.0.1"
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j" }
org-slf4j-slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "org-slf4j" }
org-apache-ivy = "org.apache.ivy:ivy:2.5.3"

[plugins]
com-github-ben-manes-versions = "com.github.ben-manes.versions:0.53.0"
io-freefair-lombok = "io.freefair.lombok:9.1.0"
nl-littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:1.0.1"
